### ISSUE TITLE
Crash when not in-game and timer goes off

### ISSUE THREAD

**Issue by MrTubzy456** [tiffit/TODOList#4]
Just like it says I crashed when I was at the title screen and a deadline had been reached. I was testing out the new deadlines feature and Cauli decided to restart the server. Well while I waited at the title screen my client crashed because the deadline had been reached but I wasn't in-game.

Here's the pastebin: http://pastebin.com/nGxfEFaM

**Comment by tiffit** [comment]
Thanks, fixed.
