### ISSUE TITLE
TODOList v1.1.1 MC 1.10 Crash on Startup

### ISSUE THREAD

**Issue by de-Rick** [tiffit/TODOList#6]
Hey,

When I try to start TODOList on MC 1.10 my Minecraft crashes, when it tries to start.

[crash-2016-07-02_12.53.28-client.txt](https://github.com/tiffit/TODOList/files/344527/crash-2016-07-02_12.53.28-client.txt)

**Comment by tiffit** [comment]
This has been fixed on the latest version
